apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplte
metadata:
  name: whalesay-workflow
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]