apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  arguments:
    parameters:
    - name: messages
      value: |
        [
          { "message": "foo" },
          { "message": "bar" },
          { "message": "baz" }
        ]

  templates:
  - name: loop-example
    inputs:
      parameters:
      - name: messages
    steps:
    - - name: print-message
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{item.message}}"
        withParam: "{{inputs.parameters.messages}}"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]